BACKUP DATABASE AdQA TO 
DISK = 'D:\AdQA_1_4-April-2022.BAK'
WITH INIT, NAME = 'FULL AdQA backup';



BACKUP DATABASE AdQA TO DISK = 'D:\AdQA_4-April-2022.BAK'
GO


use [master]
RESTORE DATABASE AdQA FROM DISK = 'D:\AdQA_4-April-2022.BAK' WITH RECOVERY
GO