CREATE TABLE ScanDenormalize(
    ScanDenormalize BIGINT IDENTITY(1,1) NOT NULL,
    BundleID INT NOT NULL,
	BundleCode VARCHAR(64) NOT NULL,
	BundleQuantity INT NOT NULL,
	ScannedQuantity INT NOT NULL DEFAULT 0,
	RemainingQuantity INT NOT NULL,
	StyleTemplateID INT NOT NULL,
	StyleTemplateCode VARCHAR(64) NOT NULL,
	ParentStyleTemplateID INT NULL,
	ParentStyleTemplateDescription VARCHAR(64) NOT NULL,
    CutJobID INT NOT NULL,
	CutNo VARCHAR(32) NOT NULL,
	CutQuantity INT NOT NULL,
	MarkerID INT NOT NULL,
	MarkerCode VARCHAR(64) NOT NULL,
	ProductionOrderID INT NOT NULL,
	ProductionOrderCode VARCHAR(100) NOT NULL,
	IsFollowOperationSequence BIT NOT NULL DEFAULT 0,
    SaleOrderID INT NOT NULL,
	SaleOrderCode VARCHAR(100) NOT NULL,
	Customer VARCHAR(64) NOT NULL,
	OrderQuantity INT NOT NULL,
    PieceID INT NOT NULL,
	PieceNumber INT NOT NULL,
    OperationID INT IDENTITY(1,1) NOT NULL,
	OperationCode VARCHAR(64) NOT NULL,
	OperationName VARCHAR(64) NOT NULL,
	OperationDescription VARCHAR(64) NOT NULL,
	PieceRate float NULL,
	OperationType VARCHAR(64) NOT NULL,
	OperationImageUrl VARCHAR(max) DEFAULT NULL,
	OperationThumbnailUrl VARCHAR(max) DEFAULT NULL,
    SMV float NULL,
	SectionID INT NOT NULL,
	SectionCode VARCHAR(64) NOT NULL,
	SectionDescription VARCHAR(64) NOT NULL,
    DepartmentID INT IDENTITY(1,1) NOT NULL,
	DepartmentName VARCHAR(40) NOT NULL,
    WorkerID INT NOT NULL,
	WorkerCode VARCHAR(64) NOT NULL,
	WorkerDescription VARCHAR(64) NOT NULL,
	WorkerImageUrl VARCHAR(max) DEFAULT NULL,
	WorkerThumbnailUrl VARCHAR(max) DEFAULT NULL,
	TodayCheckin DATETIME NULL,
	TodayProduction INT NULL,
    LineID INT NOT NULL,
	LineCode VARCHAR(64) NOT NULL,
	LineDescription VARCHAR(64) NOT NULL,
    MachineID INT NOT NULL,
	MachineCode VARCHAR(64) NOT NULL,
	MachineDescription VARCHAR(64) NOT NULL,
	MachineImageUrl VARCHAR(max) DEFAULT NULL,
	MachineThumbnailUrl VARCHAR(max) DEFAULT NULL,
    IsMachineDown BIT NULL,
	-- ActiveWorkerID INT NULL,
    MachineTypeID INT NOT NULL,
	MachineTypeCode VARCHAR(64) NOT NULL,
	MachineTypeDescription VARCHAR(64) NOT NULL,
	Allowance float NOT NULL,
    BoxID INT NOT NULL,
	BoxCode VARCHAR(64) NOT NULL,
	IssueDate DATETIME NOT NULL,
	CurrentAddress INT NOT NULL DEFAULT 0,
    WorkerScanID BIGINT NOT NULL,
	HasExpired BIT NOT NULL,
	EndedAt DATETIME NULL DEFAULT NULL,
	Extras VARCHAR(64) NULL DEFAULT NULL,
    ShortAddress VARCHAR(64) DEFAULT NULL,
	LongAddress VARCHAR(64) DEFAULT NULL,
	HostIP VARCHAR(64) DEFAULT NULL,
    CreatedAt datetime NOT NULL DEFAULT GETDATE(),
	UpdatedAt datetime NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Scan PRIMARY KEY (ScanDenormalize),
    CONSTRAINT UQ_Scan_BundleID_PieceID_OperationID UNIQUE(BundleID,PieceID,OperationID),
	CONSTRAINT UQ_ScanDenormalize_CutJobID_BundleCode UNIQUE (CutJobID,BundleCode),
	CONSTRAINT UQ_ScanDenormalize_StyleTemplateCode_ParentStyleTemplate UNIQUE (StyleTemplateCode,ParentStyleTemplateID),
	CONSTRAINT UQ_ScanDenormalize_ParentStyleTemplateDescription UNIQUE (ParentStyleTemplateDescription),
	CONSTRAINT UQ_ScanDenormalize_ProductionOrder_CutNo UNIQUE (ProductionOrderID,CutNo),
	CONSTRAINT UQ_ScanDenormalize_MarkerCode_ProductionOrder UNIQUE (MarkerCode,ProductionOrderID),
	CONSTRAINT UQ_ScanDenormalize_ProductionOrderCode UNIQUE (ProductionOrderCode),
	CONSTRAINT UQ_ScanDenormalize_SaleOrderCode UNIQUE (SaleOrderCode),
	CONSTRAINT UQ_ScanDenormalize_BundleID_PieceNo UNIQUE (BundleID,PieceNumber),
	CONSTRAINT UQ_ScanDenormalize_OperationCode UNIQUE (OperationCode),
	CONSTRAINT UQ_ScanDenormalize_SectionCode UNIQUE (SectionCode),
	CONSTRAINT UQ_ScanDenormalize_DepartmentName UNIQUE (DepartmentName),
	CONSTRAINT UQ_ScanDenormalize_WorkerCode UNIQUE (WorkerCode),
	CONSTRAINT UQ_ScanDenormalize_LineCode UNIQUE (LineCode),
	CONSTRAINT UQ_ScanDenormalize_MachineID_BoxID UNIQUE (MachineID,BoxID),
	CONSTRAINT UQ_ScanDenormalize_MachineCode UNIQUE (MachineCode),
	CONSTRAINT UQ_ScanDenormalize_MachineTypeCode UNIQUE (MachineTypeCode),
	CONSTRAINT UQ_ScanDenormalize_BoxCode UNIQUE (BoxCode),

);



DEFAULT NULL
DEFAULT 0
DEFAULT GETDATE()