



CREATE TABLE Scan_Denormalize(
    BundleID INT IDENTITY(1,1) NOT NULL,
	BundleCode VARCHAR(64) NOT NULL,
	BundleQuantity INT NOT NULL,
	ScannedQuantity INT NOT NULL,
	RemainingQuantity INT NOT NULL,
	CutJobID INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	StyleTemplateID INT NULL,


    StyleTemplateID INT IDENTITY(1,1) NOT NULL,
	StyleTemplateCode VARCHAR(64) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	ParentStyleTemplateID INT NULL,

    ParentStyleTemplateID INT IDENTITY(1,1) NOT NULL,
	ParentStyleTemplateDescription VARCHAR(64) NOT NULL,

    CutJobID INT IDENTITY(1,1) NOT NULL,
	CutNo VARCHAR(32) NOT NULL,
	ProductionOrderID INT NOT NULL,
	CutQuantity INT NOT NULL,
	MarkerID INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    MarkerID INT IDENTITY(1,1) NOT NULL,
	MarkerCode VARCHAR(64) NOT NULL,
	ProductionOrderID INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    ProductionOrderID INT IDENTITY(1,1) NOT NULL,
	ProductionOrderCode VARCHAR(100) NOT NULL,
	SaleOrderID INT NOT NULL,
	StyleTemplateID INT NULL,
	IsFollowOperationSequence BIT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    SaleOrderID INT IDENTITY(1,1) NOT NULL,
	SaleOrderCode VARCHAR(100) NOT NULL,
	Customer VARCHAR(64) NOT NULL,
	OrderQuantity INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    PieceID INT IDENTITY(1,1) NOT NULL,
	BundleID INT NOT NULL,
	PieceNumber INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	StyleTemplateID INT NULL,

    OperationID INT IDENTITY(1,1) NOT NULL,
	OperationCode VARCHAR(64) NOT NULL,
	OperationName VARCHAR(64) NOT NULL,
	OperationDescription VARCHAR(64) NOT NULL,
	PieceRate float NULL,
	OperationType VARCHAR(64) NOT NULL,
	OperationImageUrl VARCHAR(max) NULL,
	OperationThumbnailUrl VARCHAR(max) NULL,
	SectionID INT NOT NULL,
    DepartmentID INT NULL,
	SMV float NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	
    SectionID INT IDENTITY(1,1) NOT NULL,
	SectionCode VARCHAR(64) NOT NULL,
	SectionDescription VARCHAR(64) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,


    DepartmentID INT IDENTITY(1,1) NOT NULL,
	DepartmentName VARCHAR(40) NOT NULL,
	CreatedAt DATETIME NULL,
	UpdatedAt DATETIME NULL,


    WorkerID INT IDENTITY(1,1) NOT NULL,
	WorkerCode VARCHAR(64) NOT NULL,
	WorkerDescription VARCHAR(64) NOT NULL,
	WorkerImageUrl VARCHAR(max) NULL,
	WorkerThumbnailUrl VARCHAR(max) NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	TodayCheckin DATETIME NULL,
	TodayProduction INT NULL,

    LineID INT IDENTITY(1,1) NOT NULL,
	LineCode VARCHAR(64) NOT NULL,
	LineDescription VARCHAR(64) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    MachineID INT IDENTITY(1,1) NOT NULL,
	MachineCode VARCHAR(64) NOT NULL,
	MachineDescription VARCHAR(64) NOT NULL,
	MachineImageUrl VARCHAR(max) NULL,
	MachineThumbnailUrl VARCHAR(max) NULL,
	MachineTypeID INT NOT NULL,
	ActiveWorkerID INT NULL,
	LineID INT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	BoxID INT NULL,
	IsMachineDown BIT NULL,

    MachineTypeID INT IDENTITY(1,1) NOT NULL,
	MachineTypeCode VARCHAR(64) NOT NULL,
	MachineTypeDescription VARCHAR(64) NOT NULL,
	Allowance float NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

    BoxID INT IDENTITY(1,1) NOT NULL,
	BoxCode VARCHAR(64) NOT NULL,
	IssueDate DATETIME NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	CurrentAddress INT NOT NULL,

    WorkerScanID BIGINT IDENTITY(1,1) NOT NULL,
	WorkerID INT NOT NULL,
	LineID INT NOT NULL,
	MachineID INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	HasExpired BIT NOT NULL,
	EndedAt DATETIME NULL,
	Extras VARCHAR(64) NULL,
)